# -*- coding: utf-8 -*-
"""Genera los dos .hjson de TerrakeepMod (es-ES y en-US) a partir de UNA sola tabla.

Se hace asi, y no editando los dos archivos a mano, para que sea IMPOSIBLE que a un idioma le
falte una clave que el otro si tiene: la fuente es una lista de (clave, español, ingles) y los
dos archivos salen de ella. Son ~430 claves; a mano se descuadran solos.

Uso:  python scripts/generar-localizacion.py

Dos reglas que comprueba el propio script y que conviene no saltarse:
  - ninguna clave repetida;
  - ningun valor puede empezar ni acabar con un espacio (ver la nota de mas abajo: tModLoader
    reescribe los .hjson y se los come).

Ojo: tModLoader REESCRIBE estos archivos al cargar el mod. Normaliza el formato (quita las
comillas que no hacen falta y separa los bloques con una linea en blanco), asi que el .hjson
que sale de aqui y el que deja el juego se ven distintos aunque digan exactamente lo mismo. Lo
que se comitea es el del JUEGO, para que "git status" quede limpio despues de jugar: se ejecuta
este script, se lanza el mod una vez, y se comitea lo que quede.
"""
import io, os, json, collections

# (clave, es, en)
T = [
    # ---------------------------------------------------------------- panel
    ("Panel.Titulo", "Terrakeep", "Terrakeep"),
    ("Panel.Cerrar", "Cerrar ({0})", "Close ({0})"),
    ("Panel.Atajo", "Atajo: {0}", "Shortcut: {0}"),
    ("Panel.Area.Personaje", "Personaje", "Character"),
    ("Panel.Area.Libreria", "Librería", "Library"),
    ("Panel.Area.Builds", "Builds", "Builds"),
    ("Panel.Area.Investigacion", "Investigación", "Research"),
    ("Panel.Area.Exploracion", "Exploración", "Exploration"),
    ("Panel.Area.Ajustes", "Ajustes", "Settings"),
    ("Panel.Ayuda.Personaje",
     "Todo lo que toques aquí se escribe al instante sobre el personaje cargado.",
     "Everything you touch here is written straight to the loaded character."),
    ("Panel.Ayuda.Libreria",
     "Coge objetos del catálogo con el ratón y suéltalos en cualquier contenedor real.",
     "Grab items from the catalogue with the mouse and drop them into any real container."),
    ("Panel.Ayuda.Builds",
     "Auto-equipar solo MUEVE lo que ya tienes: nunca crea objetos.",
     "Auto-equip only MOVES what you already have: it never creates items."),
    ("Panel.Ayuda.Investigacion",
     "Se escribe por la vía oficial del Modo Viaje, así que el menú del juego refleja lo mismo.",
     "It writes through Journey Mode's official API, so the game's own menu shows the same."),
    ("Panel.Ayuda.Exploracion",
     "Arrastra el mini-mapa para moverte y usa la rueda para acercar.",
     "Drag the mini-map to pan and use the wheel to zoom."),
    ("Panel.Ayuda.Ajustes",
     "El idioma cambia en vivo. Ctrl+Z deshace cualquier acción de Terrakeep.",
     "The language changes live. Ctrl+Z undoes any Terrakeep action."),

    # ---------------------------------------------------------------- personaje
    ("Personaje.Pestana.Inventario", "Inventario", "Inventory"),
    ("Personaje.Pestana.Almacenes", "Almacenes", "Storage"),
    ("Personaje.Pestana.Equipo", "Equipo", "Equipment"),
    ("Personaje.Pestana.Buffs", "Buffs", "Buffs"),
    ("Personaje.Pestana.Apariencia", "Apariencia", "Appearance"),
    ("Personaje.Pestana.Desbloqueos", "Desbloqueos", "Unlocks"),

    ("Personaje.Nombre", "Nombre", "Name"),
    ("Personaje.SinNombre", "(sin nombre)", "(no name)"),
    ("Personaje.VidaMaxima", "Vida máxima", "Max health"),
    ("Personaje.ManaMaximo", "Maná máximo", "Max mana"),
    ("Personaje.VidaEfectiva", "{0} (efectiva {1})", "{0} (effective {1})"),
    ("Personaje.ManaEfectivo", "{0} (efectivo {1})", "{0} (effective {1})"),
    ("Personaje.Ahora", "Ahora: {0}/{1} vida, {2}/{3} maná", "Now: {0}/{1} health, {2}/{3} mana"),
    ("Personaje.Llenar", "Llenar vida y maná", "Refill health and mana"),
    ("Personaje.Dinero", "Dinero: {0}  (inventario {1} | almacenes {2})",
     "Money: {0}  (inventory {1} | storage {2})"),

    ("Personaje.Moneda.Platino", "plat", "plat"),
    ("Personaje.Moneda.Oro", "oro", "gold"),
    ("Personaje.Moneda.Plata", "plata", "silver"),
    ("Personaje.Moneda.Cobre", "cobre", "copper"),

    ("Personaje.Inventario.Mochila", "Mochila - 50 ranuras (Player.inventory[0..49])",
     "Backpack - 50 slots (Player.inventory[0..49])"),
    ("Personaje.Inventario.Monedas", "Monedas (50-53)", "Coins (50-53)"),
    ("Personaje.Inventario.Municion", "Munición (54-57)", "Ammo (54-57)"),
    ("Personaje.Inventario.Nota",
     "Arrastra, apila y usa el clic derecho igual que en el inventario del juego: es el mismo ItemSlot de vanilla.",
     "Drag, stack and right-click exactly like in the game's inventory: it is vanilla's own ItemSlot."),
    ("Personaje.Inventario.Ocupacion", "Mochila: {0} de {1} ranuras ocupadas.",
     "Backpack: {0} of {1} slots in use."),

    ("Personaje.Almacenes.Nombre.Hucha", "Hucha", "Piggy Bank"),
    ("Personaje.Almacenes.Nombre.Caja", "Caja fuerte", "Safe"),
    ("Personaje.Almacenes.Nombre.Forja", "Forja del Defensor", "Defender's Forge"),
    ("Personaje.Almacenes.Nombre.Boveda", "Bóveda del Vacío", "Void Vault"),
    ("Personaje.Almacenes.Titulo", "{0} - {1} ranuras (Player.{2}.item)",
     "{0} - {1} slots (Player.{2}.item)"),
    ("Personaje.Almacenes.Ocupacion", "{0}: {1} de {2} ranuras ocupadas.",
     "{0}: {1} of {2} slots in use."),

    ("Personaje.Equipo.Conjunto", "Conjunto de equipo", "Equipment loadout"),
    ("Personaje.Equipo.ConjuntoN", "Conjunto {0}", "Loadout {0}"),
    ("Personaje.Equipo.Nota",
     "El conjunto activo se edita en Player.armor/dye; cambiar de conjunto usa Player.TrySwitchingLoadout (no funciona muerto ni usando un objeto).",
     "The active loadout lives in Player.armor/dye; switching uses Player.TrySwitchingLoadout (it does not work while dead or using an item)."),
    ("Personaje.Equipo.Equipado", "Equipado", "Worn"),
    ("Personaje.Equipo.Vanidad", "Vanidad", "Vanity"),
    ("Personaje.Equipo.Tinte", "Tinte", "Dye"),
    ("Personaje.Equipo.Cabeza", "Cabeza", "Head"),
    ("Personaje.Equipo.Pecho", "Pecho", "Chest"),
    ("Personaje.Equipo.Piernas", "Piernas", "Legs"),
    ("Personaje.Equipo.Accesorio", "Accesorio {0}", "Accessory {0}"),
    ("Personaje.Equipo.NoActiva", "{0}  (no activa)", "{0}  (inactive)"),
    ("Personaje.Equipo.Especial", "Equipo especial", "Special equipment"),
    ("Personaje.Equipo.Puesto", "Puesto", "Equipped"),
    ("Personaje.Equipo.Misc.Mascota", "Mascota", "Pet"),
    ("Personaje.Equipo.Misc.MascotaLuz", "Mascota de luz", "Light pet"),
    ("Personaje.Equipo.Misc.Vagoneta", "Vagoneta", "Minecart"),
    ("Personaje.Equipo.Misc.Montura", "Montura", "Mount"),
    ("Personaje.Equipo.Misc.Gancho", "Gancho", "Grappling hook"),
    ("Personaje.Equipo.RanurasActivas",
     "Ranuras de accesorio activas: {0} de 7",
     "Active accessory slots: {0} of 7"),
    ("Personaje.Equipo.Leyenda", "Columnas: equipado · vanidad · tinte",
     "Columns: worn · vanity · dye"),
    ("Personaje.Equipo.LeyendaMisc", "Columnas: puesto · tinte", "Columns: equipped · dye"),

    # Fila de herramientas (papelera + editor de cantidad), compartida por Inventario, Almacenes
    # y Equipo.
    ("Personaje.Herramientas.Papelera", "Papelera", "Trash"),
    ("Personaje.Herramientas.CantidadObjetivo", "Cantidad de \"{0}\" ({1}/{2}):",
     "Quantity of \"{0}\" ({1}/{2}):"),
    ("Personaje.Herramientas.CantidadSinObjetivo",
     "Cantidad: pasa el ratón por un objeto con más de 1 unidad",
     "Quantity: hover an item with more than 1 unit"),
    ("Personaje.Herramientas.CantidadPista", "cantidad", "quantity"),
    ("Personaje.Herramientas.CantidadAplicar", "Aplicar", "Apply"),
    ("Personaje.Herramientas.CantidadAyuda",
     "Escribe un número y pulsa Aplicar (o Intro), o usa - / +. El límite es el máximo real del objeto.",
     "Type a number and press Apply (or Enter), or use - / +. The limit is the item's real maximum."),
    ("Personaje.Herramientas.CantidadHistorial", "Cantidad de \"{0}\": {1} -> {2}",
     "Quantity of \"{0}\": {1} -> {2}"),

    ("Personaje.Buffs.Activos", "Buffs activos: {0} de {1} ranuras",
     "Active buffs: {0} of {1} slots"),
    ("Personaje.Buffs.QuitarTodos", "Quitar todos", "Remove all"),
    ("Personaje.Buffs.Quitar", "Quitar", "Remove"),
    ("Personaje.Buffs.NombreConId", "{0}  (id {1})", "{0}  (id {1})"),
    ("Personaje.Buffs.Permanente", "permanente", "permanent"),
    ("Personaje.Buffs.HorasMinutos", "{0} h {1} min", "{0} h {1} min"),
    ("Personaje.Buffs.Anadir", "Añadir un buff", "Add a buff"),
    ("Personaje.Buffs.Buscar", "Buscar", "Search"),
    ("Personaje.Buffs.PistaBusqueda", "nombre o id del buff", "buff name or id"),
    ("Personaje.Buffs.Segundos", "Segundos", "Seconds"),
    ("Personaje.Buffs.Nota",
     "Se aplica con Player.AddBuff (API oficial): respeta inmunidades y límites.",
     "Applied with Player.AddBuff (the official API): it respects immunities and limits."),
    ("Personaje.Buffs.SinResultados", "Sin resultados.", "No results."),
    ("Personaje.Buffs.Aplicar", "Aplicar", "Apply"),

    ("Personaje.Buffs.Arbol.Inicio", "Inicio", "Home"),
    ("Personaje.Buffs.Arbol.InicioAyuda", "Vuelve a las carpetas de primer nivel",
     "Back to the top-level folders"),
    ("Personaje.Buffs.Arbol.Subir", "< Subir", "< Up"),
    ("Personaje.Buffs.Arbol.SubirAyuda", "Sube a la carpeta de arriba", "Go up one folder"),
    ("Personaje.Buffs.Arbol.Raiz", "Buffs", "Buffs"),
    ("Personaje.Buffs.Arbol.SinSubcarpetas",
     "Esta carpeta no tiene subcarpetas.\nSus buffs están a la derecha.",
     "This folder has no subfolders.\nIts buffs are on the right."),
    ("Personaje.Buffs.Arbol.CarpetaBuffs", "{0}\n{1} buffs", "{0}\n{1} buffs"),
    ("Personaje.Buffs.Arbol.CarpetaConSubcarpetas", "{0}\n{1} buffs, {2} subcarpetas",
     "{0}\n{1} buffs, {2} subfolders"),
    ("Personaje.Buffs.Arbol.CarpetaDeMod", "{0} (mod)", "{0} (mod)"),
    ("Personaje.Buffs.Arbol.Otros", "Otros", "Other"),
    ("Personaje.Buffs.Arbol.Pagina", "Página {0}", "Page {0}"),
    ("Personaje.Buffs.Arbol.Cargando", "Cargando los buffs...", "Loading the buffs..."),
    ("Personaje.Buffs.Arbol.EnCarpeta", "en \"{0}\"", "in \"{0}\""),
    ("Personaje.Buffs.Arbol.EnTodo", "en todos los buffs aplicables", "across all applicable buffs"),
    ("Personaje.Buffs.Arbol.ElegirCarpeta", "{0} buffs aplicables. Elige una carpeta o busca.",
     "{0} applicable buffs. Pick a folder or search."),
    ("Personaje.Buffs.Arbol.MostrandoParcial", "Mostrando {0} de {1} {2}.", "Showing {0} of {1} {2}."),
    ("Personaje.Buffs.Arbol.MostrandoTodos", "{0} buffs {1}.", "{0} buffs {1}."),

    ("Personaje.Apariencia.Vista", "Vista previa", "Preview"),
    ("Personaje.Apariencia.VerConArmadura", "Con armadura", "With armour"),
    ("Personaje.Apariencia.VerConArmaduraAyuda",
     "Muestra la armadura y los accesorios que llevas puestos ahora mismo, o solo la ropa base.",
     "Shows the armour and accessories you have equipped right now, or just the base outfit."),
    ("Personaje.Apariencia.Peinado", "Peinado", "Hairstyle"),
    ("Personaje.Apariencia.PeinadoValor", "{0} de {1}", "{0} of {1}"),
    ("Personaje.Apariencia.VarianteEtiqueta", "Variante / género", "Variant / gender"),
    ("Personaje.Apariencia.Variante", "{0} - {1}", "{0} - {1}"),
    ("Personaje.Apariencia.VarianteDesconocida", "Variante {0}", "Variant {0}"),
    ("Personaje.Apariencia.Genero.Hombre", "Hombre", "Male"),
    ("Personaje.Apariencia.Genero.Mujer", "Mujer", "Female"),
    ("Personaje.Apariencia.Atuendo.Inicial", "inicial", "starter"),
    ("Personaje.Apariencia.Atuendo.Pegatina", "pegatina", "sticker"),
    ("Personaje.Apariencia.Atuendo.Gangster", "gánster", "gangster"),
    ("Personaje.Apariencia.Atuendo.Abrigo", "abrigo", "coat"),
    ("Personaje.Apariencia.Atuendo.Vestido", "vestido", "dress"),
    ("Personaje.Apariencia.Atuendo.Maniqui", "maniquí", "display doll"),
    ("Personaje.Apariencia.Tinte", "Tinte de pelo", "Hair dye"),
    ("Personaje.Apariencia.SinTinte", "Ninguno", "None"),
    ("Personaje.Apariencia.TinteDesconocido", "sombreador {0} (desconocido)",
     "shader {0} (unknown)"),
    ("Personaje.Apariencia.NotaTintes",
     "Tintes de pelo encontrados en el juego (incluidos los de mods): {0}, sacados de Item.hairDye en ContentSamples.",
     "Hair dyes found in the game (mods included): {0}, taken from Item.hairDye in ContentSamples."),
    ("Personaje.Apariencia.Colores", "Colores", "Colours"),
    ("Personaje.Apariencia.Canal.Rojo", "R", "R"),
    ("Personaje.Apariencia.Canal.Verde", "V", "G"),
    ("Personaje.Apariencia.Canal.Azul", "A", "B"),
    ("Personaje.Apariencia.Color.Pelo", "Pelo", "Hair"),
    ("Personaje.Apariencia.Color.Piel", "Piel", "Skin"),
    ("Personaje.Apariencia.Color.Ojos", "Ojos", "Eyes"),
    ("Personaje.Apariencia.Color.Camisa", "Camisa", "Shirt"),
    ("Personaje.Apariencia.Color.CamisetaInterior", "Camiseta interior", "Undershirt"),
    ("Personaje.Apariencia.Color.Pantalones", "Pantalones", "Trousers"),
    ("Personaje.Apariencia.Color.Zapatos", "Zapatos", "Shoes"),
    ("Personaje.Apariencia.NotaColores",
     "Los cambios se ven al instante sobre el personaje: el juego lo dibuja leyendo estos mismos campos.",
     "Changes show on the character right away: the game draws it from these very fields."),

    ("Personaje.Desbloqueos.Titulo",
     "{0} desbloqueos permanentes. Se escriben directamente en Main.LocalPlayer.",
     "{0} permanent unlocks. They are written straight to Main.LocalPlayer."),
    ("Personaje.Desbloqueos.Nota",
     "Pasa el ratón por encima de una casilla para ver el campo real de Player que toca y sus condiciones.",
     "Hover a checkbox to see the real Player field it writes and its conditions."),
]

DESBLOQUEOS = [
    ("extraAccessory", "6ª ranura de accesorio", "6th accessory slot",
     "Corazón de Demonio. Solo surte efecto en modo Experto o superior.",
     "Demon Heart. It only takes effect in Expert mode or above."),
    ("unlockedBiomeTorches", "Antorchas de bioma desbloqueadas", "Biome torches unlocked",
     "Torch God's Favor. Sin esto, la casilla de abajo no hace nada.",
     "Torch God's Favor. Without it, the checkbox below does nothing."),
    ("UsingBiomeTorches", "Antorchas de bioma activadas", "Biome torches turned on",
     "Propiedad: guarda en builderAccStatus[11] y exige el desbloqueo de arriba.",
     "A property: it stores into builderAccStatus[11] and needs the unlock above."),
    ("ateArtisanBread", "Pan de artesano comido", "Artisan Loaf eaten",
     "Artisan Loaf: permite crear cerca de cualquier estación.",
     "Artisan Loaf: lets you craft near any station."),
    ("usedAegisCrystal", "Cristal de Égida usado", "Aegis Crystal used",
     "Aegis Crystal: +defensa permanente.", "Aegis Crystal: permanent +defence."),
    ("usedAegisFruit", "Fruta de Égida usada", "Aegis Fruit used",
     "Aegis Fruit: +vida permanente.", "Aegis Fruit: permanent +life."),
    ("usedArcaneCrystal", "Cristal arcano usado", "Arcane Crystal used",
     "Arcane Crystal: +regeneración de maná permanente.",
     "Arcane Crystal: permanent +mana regeneration."),
    ("usedGalaxyPearl", "Perla galáctica usada", "Galaxy Pearl used",
     "Galaxy Pearl: +suerte permanente.", "Galaxy Pearl: permanent +luck."),
    ("usedGummyWorm", "Gusano de goma usado", "Gummy Worm used",
     "Gummy Worm: +pesca permanente.", "Gummy Worm: permanent +fishing."),
    ("usedAmbrosia", "Ambrosía usada", "Ambrosia used",
     "Ambrosia: +velocidad de minería y recolección permanente.",
     "Ambrosia: permanent +mining and gathering speed."),
    ("downedDD2EventAnyDifficulty", "Evento DD2 superado", "DD2 event beaten",
     "Ejército Antiguo derrotado alguna vez, en cualquier dificultad.",
     "Old One's Army beaten at least once, at any difficulty."),
    ("unlockedSuperCart", "Supercarrito desbloqueado", "Mechanical Cart unlocked",
     "Mechanical Cart: mejora permanente de las vagonetas.",
     "Mechanical Cart: a permanent minecart upgrade."),
    ("enabledSuperCart", "Supercarrito activado", "Mechanical Cart turned on",
     "Exige el desbloqueo de arriba (Player.UsingSuperCart comprueba los dos).",
     "Needs the unlock above (Player.UsingSuperCart checks both)."),
]
for campo, nes, nen, des, den in DESBLOQUEOS:
    T.append(("Personaje.Desbloqueos." + campo + ".Nombre", nes, nen))
    T.append(("Personaje.Desbloqueos." + campo + ".Descripcion", des, den))

T += [
    # ---------------------------------------------------------------- libreria
    ("Libreria.PistaBusqueda", "Buscar: coma = o, espacio = y, #id, .texto",
     "Search: comma = or, space = and, #id, .text"),
    ("Libreria.Limpiar", "Limpiar", "Clear"),
    ("Libreria.LimpiarAyuda", "Vacía el buscador", "Empties the search box"),
    ("Libreria.Inicio", "Inicio", "Home"),
    ("Libreria.InicioAyuda", "Vuelve a las carpetas de primer nivel",
     "Back to the top-level folders"),
    ("Libreria.Subir", "< Subir", "< Up"),
    ("Libreria.SubirAyuda", "Sube a la carpeta de arriba", "Go up one folder"),
    ("Libreria.SinSubcarpetas",
     "Esta carpeta no tiene subcarpetas.\nSus objetos están a la derecha.",
     "This folder has no subfolders.\nIts items are on the right."),
    ("Libreria.CarpetaObjetos", "{0}\n{1} objetos", "{0}\n{1} items"),
    ("Libreria.CarpetaConSubcarpetas", "{0}\n{1} objetos, {2} subcarpetas",
     "{0}\n{1} items, {2} subfolders"),
    ("Libreria.CarpetaDeMod", "{0} (mod)", "{0} (mod)"),
    ("Libreria.Pagina", "Página {0}", "Page {0}"),
    ("Libreria.SinCatalogar", "Terraria sin catalogar", "Uncatalogued Terraria"),
    ("Libreria.Cargando", "Cargando el catálogo...", "Loading the catalogue..."),
    ("Libreria.EnCarpeta", "en \"{0}\"", "in \"{0}\""),
    ("Libreria.EnTodo", "en toda la Librería", "across the whole Library"),
    ("Libreria.SinResultados", "Sin resultados {0}.", "No results {0}."),
    ("Libreria.ElegirCarpeta", "{0} objetos. Elige una carpeta o busca.",
     "{0} items. Pick a folder or search."),
    ("Libreria.MostrandoParcial", "Mostrando {0} de {1} {2}.", "Showing {0} of {1} {2}."),
    ("Libreria.MostrandoTodos", "{0} objetos {1}.", "{0} items {1}."),
    ("Libreria.AyudaDestino",
     "Clic = 1 unidad al ratón; clic derecho = pila completa. Suéltalo aquí abajo.",
     "Click = 1 unit to the mouse; right-click = a full stack. Drop it down here."),
    ("Libreria.Aviso.Sumado", "+{0} \"{1}\" en el ratón (x{2}).", "+{0} \"{1}\" on the mouse (x{2})."),
    ("Libreria.Aviso.AlMaximo", "\"{0}\" ya está al máximo en el ratón.",
     "\"{0}\" is already at its max on the mouse."),
    ("Libreria.Aviso.NoCabe", "No cabe lo que llevabas en el ratón: suéltalo antes.",
     "What you were carrying does not fit: drop it first."),
    ("Libreria.Aviso.Cogido", "\"{0}\" x{1} en el ratón: suéltalo en una ranura de abajo.",
     "\"{0}\" x{1} on the mouse: drop it in a slot below."),
    ("Libreria.Destino.Inventario.Corto", "Mochila", "Backpack"),
    ("Libreria.Destino.Inventario.Largo", "Inventario", "Inventory"),
    ("Libreria.Destino.Monedas.Corto", "Monedas", "Coins"),
    ("Libreria.Destino.Monedas.Largo", "Monedas y munición", "Coins and ammo"),
    ("Libreria.Destino.Equipo.Corto", "Equipo", "Equip"),
    ("Libreria.Destino.Equipo.Largo", "Equipo", "Equipment"),
    ("Libreria.Destino.Hucha.Corto", "Hucha", "Piggy"),
    ("Libreria.Destino.Hucha.Largo", "Hucha", "Piggy Bank"),
    ("Libreria.Destino.Caja.Corto", "Caja", "Safe"),
    ("Libreria.Destino.Caja.Largo", "Caja fuerte", "Safe"),
    ("Libreria.Destino.Forja.Corto", "Forja", "Forge"),
    ("Libreria.Destino.Forja.Largo", "Forja del Defensor", "Defender's Forge"),
    ("Libreria.Destino.Boveda.Corto", "Bóveda", "Vault"),
    ("Libreria.Destino.Boveda.Largo", "Bóveda del Vacío", "Void Vault"),

    # Mini-panel de edicion (papelera + arrastrar para seleccionar + cantidad + prefijo), en el
    # hueco de abajo a la derecha, junto a la rejilla de destino.
    ("Libreria.Herramientas.Titulo", "Editar objeto", "Edit item"),
    ("Libreria.EditorPrefijo.RecuadroTitulo", "Seleccionar", "Select"),
    ("Libreria.EditorPrefijo.RecuadroPista", "arrastra aquí", "drag here"),
    ("Libreria.EditorCantidad.SinSeleccion",
     "Cantidad: arrastra un objeto al recuadro de arriba",
     "Quantity: drag an item into the box above"),
    ("Libreria.EditorCantidad.NoApilable", "\"{0}\" no admite pila (no se puede editar la cantidad)",
     "\"{0}\" does not stack (its quantity cannot be edited)"),
    ("Libreria.EditorPrefijo.BotonSinObjetivo", "Prefijo: (nada seleccionado)", "Prefix: (nothing selected)"),
    ("Libreria.EditorPrefijo.Boton", "Prefijo: {0}", "Prefix: {0}"),
    ("Libreria.EditorPrefijo.Ayuda",
     "Elige un prefijo legal para el objeto del recuadro de selección.",
     "Pick a legal prefix for the item in the selection box."),
    ("Libreria.EditorPrefijo.Historial", "Prefijo de \"{0}\": {1} -> {2}", "Prefix of \"{0}\": {1} -> {2}"),
    ("Libreria.Prefijo.Ninguno", "Ninguno", "None"),
    ("Libreria.Prefijo.Stat.Damage", "de daño", "damage"),
    ("Libreria.Prefijo.Stat.CritChance", "de probabilidad de golpe crítico", "critical strike chance"),
    ("Libreria.Prefijo.Stat.Knockback", "de retroceso", "knockback"),
    ("Libreria.Prefijo.Stat.UseTime", "de tiempo de uso", "use time"),
    ("Libreria.Prefijo.Stat.Size", "de tamaño", "size"),
    ("Libreria.Prefijo.Stat.ShootSpeed", "de velocidad de disparo", "shot speed"),
    ("Libreria.Prefijo.Stat.ManaCost", "de coste de maná", "mana cost"),
    ("Libreria.Prefijo.Stat.Defense", "de defensa", "defense"),
    ("Libreria.Prefijo.Stat.MaxMana", "de maná máximo", "max mana"),
    ("Libreria.Prefijo.Stat.MoveSpeed", "de velocidad de movimiento", "movement speed"),
    ("Libreria.Prefijo.Stat.MeleeSpeed", "de velocidad cuerpo a cuerpo", "melee speed"),

    # ---------------------------------------------------------------- builds
    ("Builds.AutoEquipar", "Auto-equipar", "Auto-equip"),
    ("Builds.AutoEquiparAyuda",
     "Coloca en su sitio el equipo de esta build que YA tengas. Nunca crea objetos: lo que no tengas se queda como está.",
     "Puts the gear from this build that you ALREADY own into place. It never creates items: what you lack stays as it is."),
    ("Builds.SinCatalogo", "No hay ningún catálogo de builds cargado.",
     "No build catalogue is loaded."),
    ("Builds.Armadura", "Armadura", "Armour"),
    ("Builds.Armas", "Armas", "Weapons"),
    ("Builds.Accesorios", "Accesorios", "Accessories"),
    ("Builds.PrefijoSugerido", "prefijo sugerido: {0}", "suggested prefix: {0}"),
    ("Builds.NoExisteAqui", "no existe en esta partida", "does not exist in this game"),
    ("Builds.Nada", "(nada)", "(nothing)"),
    ("Builds.RanurasAccesorio", "ranuras de accesorio disponibles: {0}",
     "accessory slots available: {0}"),
    ("Builds.Tienes", "Tienes {0} de {1} objetos de esta build{2}.",
     "You have {0} of {1} items from this build{2}."),
    ("Builds.Leyenda", "Verde = ya lo tienes  ·  gris = no lo tienes  ·  rojo = no existe aquí.",
     "Green = you have it  ·  grey = you do not  ·  red = it does not exist here."),
    ("Builds.ResultadoAutoEquipar", "Auto-equipar: {0}", "Auto-equip: {0}"),
    ("Builds.NadaQueMover",
     "No tenías ningún objeto de esta build para mover. Auto-equipar solo mueve lo que ya posees, nunca crea nada.",
     "You didn't own any item from this build to move. Auto-equip only moves what you already own, never creates anything."),
    ("Builds.Resumen",
     "movidos={0}, ya colocados={1}, no los tienes={2}, sin sitio={3}, no existen aquí={4}",
     "moved={0}, already in place={1}, not owned={2}, no room={3}, not in this game={4}"),
    ("Builds.Etapa.vanilla.prehardmode", "Pre-Hardmode (listo para el Muro de Carne)",
     "Pre-Hardmode (ready for the Wall of Flesh)"),
    ("Builds.Etapa.vanilla.earlyhardmode", "Hardmode temprano (antes de los jefes mecánicos)",
     "Early Hardmode (before the mechanical bosses)"),
    ("Builds.Etapa.vanilla.endgame", "Final del juego (post Lunatic Cultist / Moon Lord)",
     "Endgame (post Lunatic Cultist / Moon Lord)"),
    ("Builds.Etapa.calamity.prehardmode", "Pre-Hardmode (listo para el Muro de Carne)",
     "Pre-Hardmode (ready for the Wall of Flesh)"),
    ("Builds.Etapa.calamity.earlyhardmode", "Hardmode (post-Plantera / pre-Golem, aprox.)",
     "Hardmode (post-Plantera / pre-Golem, roughly)"),
    ("Builds.Etapa.calamity.endgame", "Final del juego (Auric Tesla, post-Yharon/Exo Mechs)",
     "Endgame (Auric Tesla, post-Yharon/Exo Mechs)"),
    ("Builds.Clase.Melee", "Cuerpo a cuerpo", "Melee"),
    ("Builds.Clase.Ranged", "A distancia", "Ranged"),
    ("Builds.Clase.Mage", "Mago", "Mage"),
    ("Builds.Clase.Summoner", "Invocador", "Summoner"),
    ("Builds.Clase.Rogue", "Pícaro", "Rogue"),
    ("Builds.ConjuntoDestinoPildora", "Conjunto {0}", "Set {0}"),
    ("Builds.ConjuntoDestinoAyuda",
     "A cuál de los tres conjuntos de equipo (1/2/3) va la armadura y los accesorios de esta build al auto-equipar.",
     "Which of the three equipment sets (1/2/3) this build's armour and accessories go to on auto-equip."),
    ("Builds.ConjuntoActivoMarca", "(activo)", "(active)"),

    # ---------------------------------------------------------------- investigacion
    ("Investigacion.ProgresoGlobal", "Progreso global", "Overall progress"),
    ("Investigacion.Progreso", "{0} / {1} objetos ({2}%)", "{0} / {1} items ({2}%)"),
    ("Investigacion.AvisoNoViaje",
     "AVISO: no es un personaje de Modo Viaje (dificultad {0}): se guarda, pero el juego no lo usa.",
     "WARNING: this is not a Journey Mode character (difficulty {0}): it is saved, but the game ignores it."),
    ("Investigacion.EligeCarpeta", "Elige una carpeta", "Pick a folder"),
    ("Investigacion.InvestigarCarpeta", "Investigar carpeta", "Research folder"),
    ("Investigacion.InvestigarCarpetaAyuda",
     "Investiga del todo cada objeto de esta carpeta y de las que hay dentro",
     "Fully researches every item in this folder and the ones inside it"),
    ("Investigacion.QuitarCarpeta", "Quitar carpeta", "Clear folder"),
    ("Investigacion.QuitarCarpetaAyuda",
     "Deja sin investigar todo lo de esta carpeta (Ctrl+Z lo devuelve)",
     "Un-researches everything in this folder (Ctrl+Z brings it back)"),
    ("Investigacion.SoloFalta", "Solo lo que falta", "Only what is missing"),
    ("Investigacion.SoloFaltaAyuda",
     "Esconde de la lista los objetos que ya están investigados del todo",
     "Hides items that are already fully researched"),
    ("Investigacion.InvestigarTodo", "Investigar TODO", "Research EVERYTHING"),
    ("Investigacion.InvestigarTodoAyuda",
     "Investiga del todo TODOS los objetos investigables de la partida",
     "Fully researches EVERY researchable item in the game"),
    ("Investigacion.QuitarTodo", "Quitar TODA la investigación", "Clear ALL research"),
    ("Investigacion.QuitarTodoAyuda",
     "Deja el personaje sin nada investigado (Ctrl+Z lo devuelve)",
     "Leaves the character with nothing researched (Ctrl+Z brings it back)"),
    ("Investigacion.Confirmar", "¿Seguro? Pulsa otra vez", "Are you sure? Click again"),
    ("Investigacion.Investigar", "Investigar", "Research"),
    ("Investigacion.InvestigarAyuda",
     "Marca este objeto como investigado del todo, por la vía oficial del juego",
     "Marks this item as fully researched, through the game's official path"),
    ("Investigacion.Quitar", "Quitar", "Clear"),
    ("Investigacion.QuitarAyuda", "Deja este objeto sin investigar (Ctrl+Z lo devuelve)",
     "Leaves this item un-researched (Ctrl+Z brings it back)"),
    ("Investigacion.EstadoCompleto", "investigado ({0})", "researched ({0})"),
    ("Investigacion.EstadoParcial", "{0} de {1} sacrificados", "{0} of {1} sacrificed"),
    ("Investigacion.MasObjetosDentro",
     "y {0} objetos más en las carpetas de dentro. Los botones de carpeta sí actúan sobre todos.",
     "and {0} more items in the folders inside. The folder buttons do act on all of them."),
    ("Investigacion.NadaPendiente", "Nada pendiente aquí: todo está investigado.",
     "Nothing pending here: it is all researched."),
    ("Investigacion.SinInvestigables", "Esta carpeta no tiene objetos investigables.",
     "This folder has no researchable items."),
    ("Investigacion.OtrosObjetos", "Otros objetos ({0})", "Other items ({0})"),
    ("Investigacion.Chat", "Terrakeep: {0}", "Terrakeep: {0}"),
    ("Investigacion.AccionInvestigar", "Investigar {0}", "Research {0}"),
    ("Investigacion.AccionQuitar", "Quitar la investigación de {0}", "Clear the research of {0}"),
    ("Investigacion.AccionInvestigarCarpeta", "Investigar la carpeta \"{0}\"",
     "Research the folder \"{0}\""),
    ("Investigacion.AccionQuitarCarpeta", "Quitar la investigación de la carpeta \"{0}\"",
     "Clear the research of the folder \"{0}\""),
    ("Investigacion.AccionInvestigarTodo", "Investigar todo", "Research everything"),
    ("Investigacion.AccionQuitarTodo", "Quitar toda la investigación", "Clear all research"),
    ("Investigacion.MensajeInvestigado", "Investigado: {0} -> {1}", "Researched: {0} -> {1}"),
    ("Investigacion.MensajeSinInvestigar", "Sin investigar: {0} -> {1}",
     "Un-researched: {0} -> {1}"),
    ("Investigacion.MensajeCarpeta", "Carpeta \"{0}\": {1}", "Folder \"{0}\": {1}"),
    ("Investigacion.MensajeCarpetaQuitada", "Carpeta \"{0}\" sin investigar: {1}",
     "Folder \"{0}\" un-researched: {1}"),
    ("Investigacion.MensajeTodo", "Investigar todo: {0}", "Research everything: {0}"),
    ("Investigacion.MensajeTodoQuitado", "Quitada toda la investigación: {0}",
     "All research cleared: {0}"),
    ("Investigacion.Categoria.Armadura", "Armadura", "Armour"),
    ("Investigacion.Categoria.ArmaduraCascos", "Cascos", "Helmets"),
    ("Investigacion.Categoria.ArmaduraPetos", "Petos", "Chestplates"),
    ("Investigacion.Categoria.ArmaduraPerneras", "Perneras", "Leggings"),
    ("Investigacion.Categoria.Accesorios", "Accesorios", "Accessories"),
    ("Investigacion.Categoria.Armas", "Armas", "Weapons"),
    ("Investigacion.Categoria.ArmasMelee", "Cuerpo a cuerpo", "Melee"),
    ("Investigacion.Categoria.ArmasRanged", "A distancia", "Ranged"),
    ("Investigacion.Categoria.ArmasMagic", "Mágicas", "Magic"),
    ("Investigacion.Categoria.ArmasSummon", "De invocación", "Summon"),
    ("Investigacion.Categoria.ArmasOtras", "Otras", "Other"),
    ("Investigacion.Categoria.Herramientas", "Herramientas", "Tools"),
    ("Investigacion.Categoria.Bloques", "Bloques y muebles", "Blocks and furniture"),
    ("Investigacion.Categoria.Paredes", "Paredes", "Walls"),
    ("Investigacion.Categoria.Municion", "Munición", "Ammo"),
    ("Investigacion.Categoria.Consumibles", "Consumibles", "Consumables"),
    ("Investigacion.Categoria.Materiales", "Materiales", "Materials"),
    ("Investigacion.Categoria.Otros", "Otros", "Other"),

    # ---------------------------------------------------------------- exploracion
    ("Exploracion.Titulo", "Exploración del mundo", "World exploration"),
    ("Exploracion.LineaMundo", "\"{0}\"  ·  {1}  ·  {2}", "\"{0}\"  ·  {1}  ·  {2}"),
    ("Exploracion.Hardmode", "Hardmode", "Hardmode"),
    ("Exploracion.PreHardmode", "Pre-Hardmode", "Pre-Hardmode"),
    ("Exploracion.Explorado", "Explorado: {0} %", "Explored: {0} %"),
    ("Exploracion.EstasEn", "Estás en el tile {0}", "You are at tile {0}"),
    ("Exploracion.MapaListo", "Mapa del juego listo", "Game map ready"),
    ("Exploracion.MapaSinGenerar", "El mapa del juego todavía no está generado",
     "The game map has not been generated yet"),
    ("Exploracion.Pestana.Mapa", "Mapa", "Map"),
    ("Exploracion.Pestana.Busqueda", "Búsqueda", "Search"),
    ("Exploracion.Pestana.Mundo", "Este mundo", "This world"),

    ("Exploracion.Categoria.Minerales", "Minerales", "Ores"),
    ("Exploracion.Categoria.Gemas", "Gemas", "Gems"),
    ("Exploracion.Categoria.Tesoros", "Tesoros", "Treasure"),
    ("Exploracion.Categoria.Contenedores", "Contenedores", "Containers"),
    ("Exploracion.Categoria.Liquidos", "Líquidos", "Liquids"),
    ("Exploracion.Categoria.Paredes", "Paredes", "Walls"),

    ("Exploracion.Objetivo.CobreEstano", "Cobre / Estaño", "Copper / Tin"),
    ("Exploracion.Objetivo.HierroPlomo", "Hierro / Plomo", "Iron / Lead"),
    ("Exploracion.Objetivo.PlataTungsteno", "Plata / Tungsteno", "Silver / Tungsten"),
    ("Exploracion.Objetivo.OroPlatino", "Oro / Platino", "Gold / Platinum"),
    ("Exploracion.Objetivo.DemonitaCarmesita", "Demonita / Carmesita", "Demonite / Crimtane"),
    ("Exploracion.Objetivo.Meteorito", "Meteorito", "Meteorite"),
    ("Exploracion.Objetivo.Obsidiana", "Obsidiana", "Obsidian"),
    ("Exploracion.Objetivo.PiedraInfernal", "Piedra infernal", "Hellstone"),
    ("Exploracion.Objetivo.CobaltoPaladio", "Cobalto / Paladio", "Cobalt / Palladium"),
    ("Exploracion.Objetivo.MithrilOricalco", "Mithril / Oricalco", "Mythril / Orichalcum"),
    ("Exploracion.Objetivo.AdamantitaTitanio", "Adamantita / Titanio", "Adamantite / Titanium"),
    ("Exploracion.Objetivo.Clorofita", "Clorofita", "Chlorophyte"),
    ("Exploracion.Objetivo.Luminita", "Luminita", "Luminite"),
    ("Exploracion.Objetivo.FosilesDesierto", "Fósiles del desierto", "Desert fossils"),
    ("Exploracion.Objetivo.Amatista", "Amatista", "Amethyst"),
    ("Exploracion.Objetivo.Topacio", "Topacio", "Topaz"),
    ("Exploracion.Objetivo.Zafiro", "Zafiro", "Sapphire"),
    ("Exploracion.Objetivo.Esmeralda", "Esmeralda", "Emerald"),
    ("Exploracion.Objetivo.Rubi", "Rubí", "Ruby"),
    ("Exploracion.Objetivo.Diamante", "Diamante", "Diamond"),
    ("Exploracion.Objetivo.GemasIncrustadas", "Gemas incrustadas", "Embedded gems"),
    ("Exploracion.Objetivo.CorazonesCristal", "Corazones de cristal", "Life Crystals"),
    ("Exploracion.Objetivo.FrutosVida", "Frutos de la vida", "Life Fruit"),
    ("Exploracion.Objetivo.OrbesSombra", "Orbes de sombra / Corazones",
     "Shadow Orbs / Crimson Hearts"),
    ("Exploracion.Objetivo.AltaresDemoniacos", "Altares demoníacos", "Demon Altars"),
    ("Exploracion.Objetivo.AltarLihzahrd", "Altar lihzahrd", "Lihzahrd Altar"),
    ("Exploracion.Objetivo.BulbosPlantera", "Bulbos de Plantera", "Plantera's Bulbs"),
    ("Exploracion.Objetivo.Colmenas", "Colmenas", "Hives"),
    ("Exploracion.Objetivo.LarvasAbeja", "Larvas de abeja reina", "Queen Bee Larvae"),
    ("Exploracion.Objetivo.Cofres", "Cofres y cómodas", "Chests and dressers"),
    ("Exploracion.Objetivo.Npcs", "NPC vivos ahora mismo", "NPCs alive right now"),
    ("Exploracion.Objetivo.Agua", "Agua", "Water"),
    ("Exploracion.Objetivo.Lava", "Lava", "Lava"),
    ("Exploracion.Objetivo.Miel", "Miel", "Honey"),
    ("Exploracion.Objetivo.Fulgor", "Fulgor", "Shimmer"),
    ("Exploracion.Objetivo.Mazmorra", "Mazmorra", "Dungeon"),
    ("Exploracion.Objetivo.TemploLihzahrd", "Templo lihzahrd", "Lihzahrd Temple"),
    ("Exploracion.Objetivo.NidoArana", "Nido de araña", "Spider nest"),

    ("Exploracion.SoloExplorado", "Solo en lo que ya he explorado", "Only where I have explored"),
    ("Exploracion.SoloExploradoAyuda",
     "Con esto activado, la búsqueda solo cuenta los tiles que ya has descubierto en el mapa. Desactívalo para buscar en TODO el mundo, incluido lo que no has visto nunca.",
     "With this on, the search only counts tiles you have already revealed on the map. Turn it off to search the WHOLE world, including what you have never seen."),
    ("Exploracion.Buscar", "Buscar en el mundo", "Search the world"),
    ("Exploracion.Buscando", "Buscando \"{0}\"...  {1} %", "Searching \"{0}\"...  {1} %"),
    ("Exploracion.ZonasCon", "{0} zonas con \"{1}\"", "{0} areas with \"{1}\""),
    ("Exploracion.EligeQueBuscar", "Elige qué buscar y pulsa \"Buscar en el mundo\"",
     "Pick what to look for and press \"Search the world\""),
    ("Exploracion.DetalleInicial", "El mundo tiene {0} tiles.", "The world has {0} tiles."),
    ("Exploracion.BuscarAyuda",
     "La búsqueda se reparte entre fotogramas: puedes seguir jugando mientras corre.",
     "The search is spread across frames: you can keep playing while it runs."),
    ("Exploracion.DetalleEnMarcha", "{0} encontrados de momento, {1} tiles mirados.",
     "{0} found so far, {1} tiles checked."),
    ("Exploracion.DetalleTerminada", "{0} tiles encontrados en {1} mirados, en {2} ms de CPU {3}",
     "{0} tiles found out of {1} checked, in {2} ms of CPU {3}"),
    ("Exploracion.AmbitoExplorado", "(solo en lo explorado).", "(explored area only)."),
    ("Exploracion.AmbitoTodo", "(en todo el mundo).", "(across the whole world)."),
    ("Exploracion.CategoriaVacia", "Nada de esta categoría existe en esta partida.",
     "Nothing from this category exists in this game."),
    ("Exploracion.AyudaCofres",
     "Recorre Main.chest: todos los cofres y cómodas del mundo, con lo que llevan dentro.",
     "Walks Main.chest: every chest and dresser in the world, with what is inside."),
    ("Exploracion.AyudaNpcs", "Recorre Main.npc: los NPC vivos ahora mismo, con su vida real.",
     "Walks Main.npc: the NPCs alive right now, with their real health."),
    ("Exploracion.AyudaLiquido", "Busca este líquido en los datos de líquido de cada tile.",
     "Looks for this liquid in each tile's liquid data."),
    ("Exploracion.AyudaPared", "Tipos de pared: {0}", "Wall types: {0}"),
    ("Exploracion.AyudaTile", "Tipos de tile: {0}", "Tile types: {0}"),
    ("Exploracion.SinResultados", "No hay ni uno en el mundo (o no en lo que has explorado).",
     "There is not a single one in the world (or not in what you have explored)."),
    ("Exploracion.AquiSaldran", "Aquí saldrán los sitios donde está lo que busques.",
     "The places where what you look for is will show up here."),
    ("Exploracion.FilaResultado", "({0}, {1})  {2}  ·  a {3} tiles",
     "({0}, {1})  {2}  ·  {3} tiles away"),
    ("Exploracion.AyudaResultado", "Pulsa para verlo en el mini-mapa.",
     "Click to see it on the mini-map."),

    ("Exploracion.Mapa.Acercar", "Acercar  +", "Zoom in  +"),
    ("Exploracion.Mapa.AcercarAyuda", "También puedes usar la rueda del ratón sobre el mapa.",
     "You can also use the mouse wheel over the map."),
    ("Exploracion.Mapa.Alejar", "Alejar  −", "Zoom out  −"),
    ("Exploracion.Mapa.Centrar", "Centrar en mí", "Centre on me"),
    ("Exploracion.Mapa.MundoEntero", "Ver el mundo entero", "See the whole world"),
    ("Exploracion.Mapa.VerEnMapa", "Ver en el mapa del juego", "Open the game map"),
    ("Exploracion.Mapa.VerEnMapaAyuda",
     "Cierra Terrakeep y abre el mapa grande del juego por donde estás mirando, con los marcadores de la búsqueda encima. Al cerrarlo se vuelve aquí.",
     "Closes Terrakeep and opens the game's full-screen map where you are looking, with the search markers on top. Closing it brings you back here."),
    ("Exploracion.Mapa.AvisoExclusivo",
     "El mapa grande del juego no puede\nconvivir con este panel: al abrirlo,\nTerrakeep se cierra y vuelve solo.",
     "The game's full-screen map cannot\nlive alongside this panel: opening it\ncloses Terrakeep, which comes back on its own."),
    ("Exploracion.Mapa.Marcadores", "Marcadores", "Markers"),
    ("Exploracion.Mapa.ZonasDe", "{0} zonas de \"{1}\"", "{0} areas of \"{1}\""),
    ("Exploracion.Mapa.SinBusqueda", "Sin búsqueda: usa la pestaña Búsqueda",
     "No search yet: use the Search tab"),
    ("Exploracion.Mapa.Zoom", "Zoom: {0} px por tile", "Zoom: {0} px per tile"),
    ("Exploracion.Mapa.FueraDelMundo", "Fuera del mundo", "Outside the world"),
    ("Exploracion.Mapa.TileExplorado", "{2}  ·  tile {0}, {1} (explorado)",
     "{2}  ·  tile {0}, {1} (explored)"),
    ("Exploracion.Mapa.TileSinExplorar", "{2}  ·  tile {0}, {1} (sin explorar)",
     "{2}  ·  tile {0}, {1} (unexplored)"),
    ("Exploracion.Mapa.Vacio", "Nada", "Nothing"),

    ("Exploracion.Mundo.Ficha", "Ficha del mundo", "World sheet"),
    ("Exploracion.Mundo.Dato.Nombre", "Nombre", "Name"),
    ("Exploracion.Mundo.Dato.Semilla", "Semilla", "Seed"),
    ("Exploracion.Mundo.Dato.Tamano", "Tamaño", "Size"),
    ("Exploracion.Mundo.Dato.Tiles", "Tiles", "Tiles"),
    ("Exploracion.Mundo.Dato.Modo", "Modo de juego", "Game mode"),
    ("Exploracion.Mundo.Dato.Progreso", "Progreso", "Progress"),
    ("Exploracion.Mundo.Dato.MalDelMundo", "Mal del mundo", "World evil"),
    ("Exploracion.Mundo.Dato.SemillasSecretas", "Semillas secretas", "Secret seeds"),
    ("Exploracion.Mundo.Dato.Aparicion", "Aparición", "Spawn"),
    ("Exploracion.Mundo.Dato.EstasEn", "Estás en", "You are at"),
    ("Exploracion.Mundo.Dato.Explorado", "Explorado", "Explored"),
    ("Exploracion.Mundo.Dato.Autoguardado", "Autoguardado", "Autosave"),
    ("Exploracion.Mundo.ModoValor", "{0}  (Main.GameMode = {1})", "{0}  (Main.GameMode = {1})"),
    ("Exploracion.Mundo.Tile", "tile {0}", "tile {0}"),
    ("Exploracion.Mundo.Porcentaje", "{0} %", "{0} %"),
    ("Exploracion.Mundo.Activado", "activado", "on"),
    ("Exploracion.Mundo.Desactivado", "desactivado", "off"),
    ("Exploracion.Mundo.SinSemilla", "(el mundo no guarda semilla)",
     "(this world stores no seed)"),
    ("Exploracion.Mundo.Desconocido", "(desconocido)", "(unknown)"),
    ("Exploracion.Mundo.NingunaSemilla", "(ninguna)", "(none)"),
    ("Exploracion.Mundo.SinJugador", "(sin jugador)", "(no player)"),
    ("Exploracion.Mundo.Dificultad", "Dificultad del mundo, en vivo", "World difficulty, live"),
    ("Exploracion.Mundo.AhoraMismo", "Ahora mismo: {0}", "Right now: {0}"),
    ("Exploracion.Mundo.AvisoDeshacer",
     "Queda en el historial de Terrakeep: se puede deshacer con Ctrl+Z mientras no se haya guardado.",
     "It goes into Terrakeep's history: Ctrl+Z undoes it as long as nothing has been saved."),
    ("Exploracion.Mundo.EligeModo", "Elige un modo arriba", "Pick a mode above"),
    ("Exploracion.Mundo.Confirmar", "Confirmar: pasar a {0}", "Confirm: switch to {0}"),
    ("Exploracion.Mundo.NoSePuede", "No se puede: {0}", "Not possible: {0}"),
    ("Exploracion.Mundo.NoSePudo", "No se pudo: {0}", "It did not work: {0}"),
    ("Exploracion.Mundo.VasAPasar", "Vas a pasar de {0} a {1}. Pulsa el botón de confirmar.",
     "You are about to go from {0} to {1}. Press the confirm button."),
    ("Exploracion.Mundo.Hecho", "Hecho: el mundo está en modo {0}. Se grabará en el siguiente guardado.",
     "Done: the world is now in {0} mode. It will be written on the next save."),
    ("Exploracion.Mundo.AyudaModoActual", "Es el modo que tiene el mundo ahora mismo.",
     "This is the mode the world is in right now."),
    ("Exploracion.Mundo.AyudaElegirModo", "Pulsa para elegirlo; después habrá que confirmar.",
     "Click to pick it; you will have to confirm afterwards."),

    ("Exploracion.Modo.Clasico", "Clásico", "Classic"),
    ("Exploracion.Modo.Experto", "Experto", "Expert"),
    ("Exploracion.Modo.Maestro", "Maestro", "Master"),
    ("Exploracion.Modo.Viaje", "Viaje", "Journey"),
    ("Exploracion.Modo.Desconocido", "Desconocido ({0})", "Unknown ({0})"),
    ("Exploracion.Mal.Carmesi", "Carmesí", "Crimson"),
    ("Exploracion.Mal.Corrupcion", "Corrupción", "Corruption"),
    ("Exploracion.Semilla.Drunk", "Mundo borracho", "Drunk world"),
    ("Exploracion.Semilla.ForTheWorthy", "Por los que lo valen", "For the worthy"),
    ("Exploracion.Semilla.Anniversary", "10º aniversario", "10th anniversary"),
    ("Exploracion.Semilla.NotTheBees", "¡Las abejas no!", "Not the bees!"),
    ("Exploracion.Semilla.DontStarve", "Don't Starve", "Don't Starve"),
    ("Exploracion.Semilla.Remix", "Remix", "Remix"),
    ("Exploracion.Semilla.NoTraps", "Sin trampas", "No traps"),
    ("Exploracion.Semilla.Zenith", "Cénit", "Zenith"),

    ("Exploracion.Dificultad.SinMundo", "No hay ningún mundo cargado.", "No world is loaded."),
    ("Exploracion.Dificultad.Multijugador",
     "Estás en una partida multijugador: el modo del mundo lo decide el servidor.",
     "You are in a multiplayer game: the world mode is up to the server."),
    ("Exploracion.Dificultad.YaEnEseModo", "El mundo ya está en este modo.",
     "The world is already in this mode."),
    ("Exploracion.Dificultad.ModoInexistente",
     "Este modo de juego no existe en esta versión del juego.",
     "This game mode does not exist in this version of the game."),
    ("Exploracion.Dificultad.SinPersonaje", "No hay ningún personaje cargado.",
     "No character is loaded."),
    ("Exploracion.Dificultad.SoloViaje",
     "Tu personaje es de Viaje y solo puede entrar en mundos de Viaje: si quitas el modo Viaje de este mundo, este personaje se quedará fuera.",
     "Your character is a Journey one and can only enter Journey worlds: if you take Journey mode off this world, this character will be locked out."),
    ("Exploracion.Dificultad.NoViaje",
     "Tu personaje NO es de Viaje: si pones este mundo en modo Viaje, este personaje ya no podrá volver a entrar en él.",
     "Your character is NOT a Journey one: if you put this world into Journey mode, this character will not be able to come back in."),
    ("Exploracion.Dificultad.PermanenteAutoguardado",
     "El cambio es PERMANENTE: se escribe en el mundo en el siguiente autoguardado (lo tienes activado).",
     "The change is PERMANENT: it is written to the world on the next autosave (which you have on)."),
    ("Exploracion.Dificultad.PermanenteAlGuardar",
     "El cambio es PERMANENTE: se escribe en el mundo en cuanto se guarde (tienes el autoguardado desactivado, pero salir al menú guarda igual).",
     "The change is PERMANENT: it is written to the world as soon as it saves (autosave is off, but leaving to the menu saves anyway)."),
    ("Exploracion.Dificultad.Efecto",
     "Los enemigos ya generados no cambian de vida ni de daño hasta que reaparezcan; el botín sí reacciona al instante.",
     "Enemies that already spawned keep their health and damage until they respawn; loot does react right away."),

    # ---------------------------------------------------------------- ajustes (WS7)
    ("Ajustes.Titulo", "Terrakeep - Ajustes", "Terrakeep - Settings"),
    ("Ajustes.Idioma", "Idioma de la interfaz", "Interface language"),
    ("Ajustes.IdiomaSeguirElJuego", "El del juego", "Follow the game"),
    ("Ajustes.IdiomaEspanol", "Español", "Spanish"),
    ("Ajustes.IdiomaIngles", "English", "English"),
    ("Ajustes.CulturaActiva", "Idioma activo del juego ahora mismo: {0}",
     "Game language in use right now: {0}"),
    ("Ajustes.Cerrar", "Cerrar", "Close"),
    ("Ajustes.Historial", "Deshacer y rehacer", "Undo and redo"),
    ("Ajustes.HistorialVacio", "No hay nada en el historial de esta sesión.",
     "Nothing in this session's history yet."),
    ("Ajustes.HistorialEntradas", "Acciones guardadas en el historial: {0}",
     "Actions stored in the history: {0}"),
    ("Ajustes.Deshacer", "Deshacer (Ctrl+Z)", "Undo (Ctrl+Z)"),
    ("Ajustes.Rehacer", "Rehacer (Ctrl+Y)", "Redo (Ctrl+Y)"),
    ("Ajustes.DeshacerAlgo", "Deshacer: {0}", "Undo: {0}"),
    ("Ajustes.RehacerAlgo", "Rehacer: {0}", "Redo: {0}"),
    ("Ajustes.Atajos", "Atajos de teclado", "Keybinds"),
    ("Ajustes.AtajosNota",
     "Cada tecla abre Terrakeep directamente en su pestaña. Reasignables en Ajustes > Controles del juego.",
     "Each key opens Terrakeep straight on its own tab. Rebindable in the game's Settings > Controls."),
    ("Ajustes.AtajosHistorial", "Deshacer y rehacer: {0} y {1} (con Ctrl pulsado).",
     "Undo and redo: {0} and {1} (holding Ctrl)."),
    ("Ajustes.AtajosIcono",
     "También se abre con el icono de Terrakeep, junto al bestiario y los emotes, cuando tienes el inventario abierto.",
     "It also opens from the Terrakeep icon next to the bestiary and emote buttons, while the inventory is open."),
    ("Ajustes.SinTecla", "[sin tecla]", "[no key]"),

    # ---------------------------------------------------------------- historial
    ("Historial.Deshecho", "Terrakeep ha deshecho: {0}", "Terrakeep undid: {0}"),
    ("Historial.Rehecho", "Terrakeep ha rehecho: {0}", "Terrakeep redid: {0}"),
    ("Historial.NadaQueDeshacer", "Terrakeep no tiene nada que deshacer.",
     "Terrakeep has nothing to undo."),
    ("Historial.NadaQueRehacer", "Terrakeep no tiene nada que rehacer.",
     "Terrakeep has nothing to redo."),

    # ---------------------------------------------------------------- prefijos
    ("Prefijos.MejorPrefijo", "Mejor prefijo posible: {0}", "Best possible prefix: {0}"),
]

KEYBINDS = [
    ("AbrirPanel", "Abrir Terrakeep", "Open Terrakeep"),
    ("AbrirLibreria", "Abrir la Librería de Terrakeep", "Open Terrakeep Library"),
    ("AbrirBuilds", "Abrir las Builds de Terrakeep", "Open Terrakeep Builds"),
    ("AbrirInvestigacion", "Abrir la Investigación de Terrakeep", "Open Terrakeep Research"),
    ("AbrirExploracion", "Abrir la Exploración de Terrakeep", "Open Terrakeep Exploration"),
    ("AbrirAjustes", "Abrir los Ajustes de Terrakeep", "Open Terrakeep Settings"),
    ("Deshacer", "Deshacer (con Ctrl)", "Undo (hold Ctrl)"),
    ("Rehacer", "Rehacer (con Ctrl)", "Redo (hold Ctrl)"),
]

CONFIG = {
    "es": {
        "DisplayName": "Ajustes",
        "Header": "Interfaz",
        "IdiomaLabel": "Idioma de la interfaz",
        "IdiomaTooltip": "En qué idioma muestra Terrakeep sus paneles. Elegir Español o English cambia el idioma del juego entero en el acto, porque tModLoader tiene un único idioma activo para todo.",
        "EnumTooltip": "",
        "SeguirElJuego": "El del juego",
        "Espanol": "Español",
        "English": "English",
    },
    "en": {
        "DisplayName": "Settings",
        "Header": "Interface",
        "IdiomaLabel": "Interface language",
        "IdiomaTooltip": "Which language Terrakeep uses for its panels. Picking Spanish or English switches the whole game's language right away, because tModLoader only has one active language at a time.",
        "EnumTooltip": "",
        "SeguirElJuego": "Follow the game",
        "Espanol": "Spanish",
        "English": "English",
    },
}


def anidar(pares):
    raiz = collections.OrderedDict()
    for clave, valor in pares:
        partes = clave.split(".")
        nodo = raiz
        for parte in partes[:-1]:
            nodo = nodo.setdefault(parte, collections.OrderedDict())
            assert isinstance(nodo, collections.OrderedDict), clave
        assert partes[-1] not in nodo, clave
        nodo[partes[-1]] = valor
    return raiz


def escribir(nodo, sangria, salida):
    tab = "\t" * sangria
    for clave, valor in nodo.items():
        if isinstance(valor, collections.OrderedDict):
            salida.append("%s%s: {" % (tab, clave))
            escribir(valor, sangria + 1, salida)
            salida.append("%s}" % tab)
        else:
            salida.append("%s%s: %s" % (tab, clave, json.dumps(valor, ensure_ascii=False)))


def generar(idioma):
    i = 1 if idioma == "es" else 2
    pares = [(x[0], x[i]) for x in T]
    # Keybinds
    for nombre, es, en in KEYBINDS:
        pares.append(("Keybinds." + nombre + ".DisplayName", es if idioma == "es" else en))
    c = CONFIG[idioma]
    pares += [
        ("Configs.AjustesConfig.DisplayName", c["DisplayName"]),
        ("Configs.AjustesConfig.Headers.Interfaz", c["Header"]),
        ("Configs.AjustesConfig.Idioma.Label", c["IdiomaLabel"]),
        ("Configs.AjustesConfig.Idioma.Tooltip", c["IdiomaTooltip"]),
        ("Configs.IdiomaDeTerrakeep.Tooltip", c["EnumTooltip"]),
        ("Configs.IdiomaDeTerrakeep.SeguirElJuego.Label", c["SeguirElJuego"]),
        ("Configs.IdiomaDeTerrakeep.SeguirElJuego.Tooltip", ""),
        ("Configs.IdiomaDeTerrakeep.Espanol.Label", c["Espanol"]),
        ("Configs.IdiomaDeTerrakeep.Espanol.Tooltip", ""),
        ("Configs.IdiomaDeTerrakeep.English.Label", c["English"]),
        ("Configs.IdiomaDeTerrakeep.English.Tooltip", ""),
    ]
    salida = []
    escribir(anidar(pares), 0, salida)
    return "\n".join(salida) + "\n"


base = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                    "Localization")
for idioma, nombre in [("es", "es-ES_Mods.TerrakeepMod.hjson"), ("en", "en-US_Mods.TerrakeepMod.hjson")]:
    ruta = os.path.join(base, nombre)
    io.open(ruta, "w", encoding="utf-8", newline="\n").write(generar(idioma))
    print("escrito", ruta)

claves = [x[0] for x in T]
assert len(claves) == len(set(claves)), "clave repetida"

# NINGUN valor puede empezar o acabar con un espacio.
#
# No es manía: tModLoader REESCRIBE los .hjson al cargar el mod (normaliza el formato y añade
# las claves que falten), y en ese viaje de ida y vuelta un valor que lleve comillas dobles
# DENTRO se guarda como cadena de triple comilla ('''...''') y al releerlo PIERDE los espacios
# de los bordes. Paso de verdad con Libreria.EnCarpeta (" en \"{0}\""), que se quedo en
# "en \"{0}\"" y hacia que el resumen del buscador dijera "Sin resultadosen ...". Los
# separadores van en la plantilla que concatena, no en el trozo.
for _clave, _es, _en in T:
    for _idioma, _valor in (("es", _es), ("en", _en)):
        assert _valor == _valor.strip(), (
            "el valor de " + _clave + " [" + _idioma + "] empieza o acaba con espacio")
print(len(T), "claves de interfaz +", len(KEYBINDS), "atajos")
